language: python
python:
  - 3.6

services:
  - docker

before_install:
  - docker build -t scharch/sonar .
  - docker run scharch/sonar python3 /SONAR/tests/run_tests.py

install: skip

script: skip
